


    barcodedata=importdata('/home/glenn/Documents/morpheus/sim_outputs/meta_barcode_data.csv');
    outputfolder='/home/glenn/Documents/morpheus/sim_outputs/';
    
    barcodesorted=sortrows(barcodedata,[3 32],'descend');

%     varsvec=[...
%         "sim_ID",...
%         "Barcode",...
%         "Fam_size",...
%         "nc_div1",...
%         "nc_divN",...
%         "contact_req",...
%         "start_myc",...
%         "sig_str",...
%         "time_a",...
%         "contact_a",...
%         "myc_gain_a",...
%         "myc_a",...
%         "time_b",...
%         "contact_b",...
%         "myc_gain_b",...
%         "myc_b",...
%         "time_d",...
%         "contact_d",...
%         "myc_gain_d",...
%         "myc_d",...
%         "time_ab",...
%         "contact_ab",...
%         "myc_gain_ab",...
%         "myc_ab",...
%         "contact_events_d",...
%         "vol_per_cell",...
%         "cells_in_sim",...
%         "cognate_in_sim",...
%         "reticular_in_sim",...
%         "max_contact_fam",...
%         "contact_events_fam",...
%         ];
%     
%     dattab=array2table(barcodesorted(:,1:length(varsvec)));
%     dattab.Properties.VariableNames=cellstr(varsvec);
%     
%     lme1=fitlme(dattab,strcat('Fam_size~1',...
%         '+sig_str',...
%         '+vol_per_cell',...
%         '+cells_in_sim',...
%         '+cognate_in_sim',...
%         '+reticular_in_sim',...
%         '+nc_div1',...
%         '+nc_divN',...
%         '+contact_req',...
%         '+start_myc',...
%         '+time_a',...
%         '+contact_a',...
%         '+myc_gain_a',...
%         '+myc_a',...
%         '+time_b',...
%         '+contact_b',...
%         '+myc_gain_b',...
%         '+myc_b',...
%         '+time_d',...
%         '+contact_d',...
%         '+myc_gain_d',...
%         '+myc_d',...
%         '+time_ab',...
%         '+contact_ab',...
%         '+myc_gain_ab',...
%         '+myc_ab',...
%         '+contact_events_d',...
%         '+max_contact_fam',...
%         '+contact_events_fam'...
%         ));
%     
%     disp(lme1)
%     disp(lme1.Rsquared)
%     
%    coeffs1=lme1.Coefficients.Estimate;
%   
%     figure;
%     thomas=axes;
%     scatter(...
%         barcodesorted(:,3),...
%         coeffs1(1)*1+...
%         coeffs1(2)*barcodesorted(:,4)+...
%         coeffs1(3)*barcodesorted(:,5)+...
%         coeffs1(4)*barcodesorted(:,6)+...
%         coeffs1(5)*barcodesorted(:,7)+...
%         coeffs1(6)*barcodesorted(:,8)+...
%         coeffs1(7)*barcodesorted(:,9)+...
%         coeffs1(8)*barcodesorted(:,10)+...
%         coeffs1(9)*barcodesorted(:,11)+...
%         coeffs1(10)*barcodesorted(:,12)+...
%         coeffs1(11)*barcodesorted(:,13)+...
%         coeffs1(12)*barcodesorted(:,14)+...
%         coeffs1(13)*barcodesorted(:,15)+...
%         coeffs1(14)*barcodesorted(:,16)+...
%         coeffs1(15)*barcodesorted(:,17)+...
%         coeffs1(16)*barcodesorted(:,18)+...
%         coeffs1(17)*barcodesorted(:,19)+...
%         coeffs1(18)*barcodesorted(:,20)+...
%         coeffs1(19)*barcodesorted(:,21)+...
%         coeffs1(20)*barcodesorted(:,22)+...
%         coeffs1(21)*barcodesorted(:,23)+...
%         coeffs1(22)*barcodesorted(:,24)+...
%         coeffs1(23)*barcodesorted(:,25)+...
%         coeffs1(24)*barcodesorted(:,26)+...
%         coeffs1(25)*barcodesorted(:,27)+...
%         coeffs1(26)*barcodesorted(:,28)+...
%         coeffs1(27)*barcodesorted(:,29)+...
%         coeffs1(28)*barcodesorted(:,30)+...
%         coeffs1(29)*barcodesorted(:,31)...
%     )
%     text(thomas,...
%              (thomas.XLim(1)+(thomas.XLim(2)-thomas.XLim(1))/2),...
%              (thomas.YLim(1)+(thomas.YLim(2)-thomas.YLim(1))*9/10),...
%              {...
%                 cat(2,'R-squared (ordinary): ',num2str(lme1.Rsquared.Ordinary)),...
%                 cat(2,'R-squared (adjusted): ',num2str(lme1.Rsquared.Adjusted))...
%              },...
%              'Color','k'...
%          )
%     
%     
%     lme2=fitlme(dattab,strcat('Fam_size~1',...
%         '+myc_d',...
%         '+contact_events_d',...
%         '+max_contact_fam',...
%         '+contact_events_fam'...
%         ));
%     
%     disp(lme2)
%     disp(lme2.Rsquared)
%      
%    coeffs=lme2.Coefficients.Estimate;
%    
%     figure;
%     thomas=axes;
%     scatter(...
%         barcodesorted(:,3),...
%         coeffs(1)*1+...
%         coeffs(2)*barcodesorted(:,20)+...
%         coeffs(3)*barcodesorted(:,25)+...
%         coeffs(4)*barcodesorted(:,30)+...
%         coeffs(5)*barcodesorted(:,31)...
%         )
%     text(thomas,...
%              (thomas.XLim(1)+(thomas.XLim(2)-thomas.XLim(1))/2),...
%              (thomas.YLim(1)+(thomas.YLim(2)-thomas.YLim(1))*9/10),...
%              {...
%                 cat(2,'R-squared (ordinary): ',num2str(lme1.Rsquared.Ordinary)),...
%                 cat(2,'R-squared (adjusted): ',num2str(lme1.Rsquared.Adjusted))...
%              },...
%              'Color','k'...
%          )
% 
%     
%     lme4=fitlme(dattab,strcat('Fam_size~1',...
%         '+nc_div1',...
%         '+nc_divN',...
%         '+contact_req',...
%         '+sig_str',...
%         '+time_a',...
%         '+time_b',...
%         '+myc_d',...
%         '+time_ab',...
%         '+myc_ab',...
%         '+contact_events_d',...
%         '+cells_in_sim',...
%         '+contact_events_fam'...
%         ));
%     
%     disp(lme4)
%     disp(lme4.Rsquared)
%     
%     lme3=fitlme(dattab,strcat('Fam_size~',...
%         'sig_str',...
%         '+vol_per_cell',...
%         '+cells_in_sim',...
%         '+cognate_in_sim',...
%         '+reticular_in_sim',...
%         '+nc_div1',...
%         '+nc_divN',...
%         '+contact_req',...
%         '+start_myc',...
%         '+time_a',...
%         '+contact_a',...
%         '+myc_gain_a',...
%         '+myc_a',...
%         '+time_b',...
%         '+contact_b',...
%         '+myc_gain_b',...
%         '+myc_b',...
%         '+time_d',...
%         '+contact_d',...
%         '+myc_gain_d',...
%         '+myc_d',...
%         '+time_ab',...
%         '+contact_ab',...
%         '+myc_gain_ab',...
%         '+myc_ab',...
%         '+contact_events_d',...
%         '+max_contact_fam',...
%         '+contact_events_fam',...
%         ...
%         '+(start_myc|sig_str)',...
%         '+(myc_gain_a|sig_str)',...
%         '+(myc_a|sig_str)',...
%         '+(myc_gain_d|sig_str)',...
%         '+(myc_gain_ab|sig_str)',...
%         ...
%         '+(contact_a|contact_req)',...
%         '+(contact_d|contact_req)',...
%         '+(contact_ab|contact_req)',...
%         ...
%         '+(contact_b|time_b)',...
%         '+(myc_gain_b|time_b)',...
%         '+(myc_b|time_b)',...
%         ...
%         '+(time_d|time_a)',...
%         ...
%         '+(vol_per_cell|cells_in_sim)',...
%         '+(reticular_in_sim|cells_in_sim)'...
%         ...
%        ));
%     
%     disp(lme3)
%     disp(lme3.Rsquared)
    
    
    mdl=stepwiselm(barcodesorted(:,4:32),barcodesorted(:,3)','quadratic');
    